system:
  host: localhost
  port: 3001
  env: dev
mysql:
  host: 127.0.0.1
  port: 3306
  dbName: NectarPin
  dbUser: NectarPin
  dbPassword: 12345678
logger:
  level: info
  prefix: '[NectarPin]'
  director: log
  showLine: true
  logInConsole: true
